In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils._bunch.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data

In [7]:
# X

In [8]:
y = iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
# class 0 --> [1, 0, 0]
# class 1 --> [0, 1, 0]
# class 2 --> [0, 0, 1]

In [11]:
from keras.utils import to_categorical

2023-08-22 22:35:26.936217: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [12]:
y = to_categorical(y)

In [13]:
y.shape

(150, 3)

In [14]:
# y

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
# y_test

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
# np.array([5, 10, 15, 20])/20

In [20]:
scaler_object = MinMaxScaler()

In [21]:
scaler_object.fit(X_train)

MinMaxScaler()

In [22]:
scaled_X_train = scaler_object.transform(X_train)

In [23]:
scaled_X_test = scaler_object.transform(X_test)

In [24]:
# scaled_X_train

In [25]:
from keras.models import Sequential
from keras.layers import Dense

In [26]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax')) # [0.2, 0.3, 0.5]
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

2023-08-22 22:43:53.415534: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
4/4 - 0s - loss: 1.0924 - accuracy: 0.3500 - 276ms/epoch - 69ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0867 - accuracy: 0.3500 - 3ms/epoch - 716us/step
Epoch 3/150
4/4 - 0s - loss: 1.0825 - accuracy: 0.3500 - 3ms/epoch - 687us/step
Epoch 4/150
4/4 - 0s - loss: 1.0776 - accuracy: 0.3500 - 3ms/epoch - 749us/step
Epoch 5/150
4/4 - 0s - loss: 1.0718 - accuracy: 0.3600 - 3ms/epoch - 846us/step
Epoch 6/150
4/4 - 0s - loss: 1.0667 - accuracy: 0.3800 - 3ms/epoch - 761us/step
Epoch 7/150
4/4 - 0s - loss: 1.0610 - accuracy: 0.3900 - 5ms/epoch - 1ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0558 - accuracy: 0.4100 - 4ms/epoch - 1ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0501 - accuracy: 0.4200 - 4ms/epoch - 903us/step
Epoch 10/150
4/4 - 0s - loss: 1.0448 - accuracy: 0.4200 - 5ms/epoch - 1ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0392 - accuracy: 0.4300 - 4ms/epoch - 931us/step
Epoch 12/150
4/4 - 0s - loss: 1.0335 - accuracy: 0.5800 - 4ms/epoch - 1ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0279 - accur

In [29]:
model.predict_classes(scaled_X_test)

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [30]:
# y_test

In [31]:
predictions = np.argmax(model.predict(scaled_X_test), axis=1)

2/2 [==============================] - 0s 2ms/step


In [32]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [33]:
# y_test

In [34]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [35]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 16]])

In [36]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.87      0.93        15
           2       0.89      1.00      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [37]:
accuracy_score(y_test.argmax(axis=1), predictions)

0.96

In [38]:
model.save('myfirstmodel.h5')

In [39]:
from keras.models import load_model

In [40]:
new_model = load_model('myfirstmodel.h5')

In [41]:
np.argmax(new_model.predict(scaled_X_test), axis=1)

2/2 [==============================] - 0s 2ms/step


array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])